name: Continuous Integration (CI) 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: apt-get install libreadline6; make
    - name: make check
      run: apt-get install libreadline6; make check
